---

- name: Check localhost
  hosts: all
    #become: true

  tasks:

    - name: Deploy template
      ansible.builtin.template:
        src: templates/hosts.j2
        dest: /home/dp/test.txt

    - name: Directory stuff
      block:
        - name: Create directory
          ansible.builtin.file:
            path: /home/dp/test_dir
            state: directory

        - name: Create Symlink
          ansible.builtin.file:
            src: /home/dp/test_dir
            dest: /home/dp/test_dir_2
            state: link

- name: Create users and groups
  hosts: all
  become: true
  vars_files:
    - vars/user_vars.yml
    - vars/passwords.yml

  tasks:
    - name: Create groups
      loop:
        - ansible_group_01
        - ansible_group_02
        - manager
        - developer
      ansible.builtin.group:
        name: "{{ item }}"
        state: present

    - name: Create mgmt users
      loop: "{{ users }}"
      when: item.job == "manager"
      ansible.builtin.user:
        name: "{{ item.username }}"
        groups: "{{ item.group }}"
        password: "{{ pw_manager | password_hash('sha512') }}"

    - name: Create dev users
      loop: "{{ users }}"
      when: item.job == "developer"
      ansible.builtin.user:
        name: "{{ item.username }}"
        groups: "{{ item.group }}"
        password: "{{ pw_developer | password_hash('sha512') }}"


- name: Local file
  hosts: all

  tasks:
    - name: Run report
      delegate_to: localhost
      changed_when: false
      ansible.builtin.template:
        src: templates/report.j2
        dest: /home/dperrone/development/ansible/playbooks/demo-playbook/output.txt
        mode: '0644'

- name: Add line to the report
  hosts: localhost

  tasks:
    - name: Add line to the report.
      delegate_to: localhost
      ansible.builtin.lineinfile:
        path: /home/dperrone/development/ansible/playbooks/demo-playbook/output.txt
        line: "test from {{ ansible_hostname }}"
